<?php include "include/head.php"?>
<!doctype html>
<html lang="en">

<head>
<meta charset="utf-8">
<!--[if IE]>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<![endif]-->
<title>OTP! - Shreekrishna International Donate Fund</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- Place favicon.ico in the root directory -->
<link rel="apple-touch-icon" href="apple-touch-icon.png">
<link rel="icon" href="favicon.ico">
<link href="https://fonts.googleapis.com/css?family=Poppins:100,300,400,700,900" rel="stylesheet">
<!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800" rel="stylesheet"> -->
<link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
<!-- themeforest:css -->
<link rel="stylesheet" href="css/vendor.min.css">
<link rel="stylesheet" href="css/dashcore.min.css">
<!-- endinject -->
</head>
<body>

<main>
<div class="container-fluid">
<div class="row align-items-center">
<div class="col-md-6 col-lg-7 fullscreen-md d-flex justify-content-center align-items-center overlay gradient gradient-53 alpha-7 image-background cover" style="background-image:url(https://picsum.photos/1920/1200/?random&amp;gravity=west)">
<div class="content">
<h2 class="display-4 display-md-3 color-1 mt-4 mt-md-0">One Time Password<span class="bold d-block"></span>
</h2>
<p class="lead color-1 alpha-5">Check Your Mobile For The OTP!</p>
<!-- <hr class="mt-md-6 w-25"> -->

</div>
</div>
<div class="col-md-5 col-lg-4 mx-auto">
<div class="forgot-form mt-5 mt-md-0">
<img src="skidf_final.png" class="logo img-responsive mb-4 mb-md-6" style="margin-left: 120px;" alt="Logo">
<?php
                //banner background
                 if(isset($_POST['otpsubmit'])){
                   check_all_var(); //prevent mysql injection 

     $selectotp=mysqli_query($link,"SELECT * FROM `".$prefix."otp` WHERE `phone`=".$_REQUEST['pid']);
     $fetchotp=mysqli_fetch_object($selectotp);

     if($_POST['otpgiven']!=$fetchotp->otp)
     { 

        echo '<p class="alert alert-danger" id="success-alert"><i class="fa fa-check fa-fw"></i>Invalid OTP!</p>'; 

}
     
     else {

     mysqli_query($link,"INSERT `".$prefix."register` SET `side_img`='".$fetchotp->side_img."', `gender`='".$fetchotp->gender."', 
     `reference_no`='".$fetchotp->reference_no."',`name`='".$fetchotp->name."', `dob`='".$fetchotp->dob."', `pincode`='".$fetchotp->pincode."', `email`='".$fetchotp->email."', `area`='".$fetchotp->area."', 
     `phone`='".$fetchotp->phone."', `profession`='".$fetchotp->profession."', `password`='".$fetchotp->password."', `salary`='".$fetchotp->salary."', 
     `state`='".$fetchotp->state."', `academic`='".$fetchotp->academic."', `status`='pending',`fhash`='',`address`='".$fetchotp->address."'");

      //   $last_id=mysqli_insert_id($link);
        
      // mysqli_query($link,"INSERT `".$prefix."register_kyc` SET `pancard`='', `reg_id`='".$last_id."',`pan_img`='',`address_type`='',`address_img`='',`status`='0'");

      // mysqli_query($link,"INSERT `".$prefix."register_bank` SET `account_holder`='', `reg_id`='".$last_id."',`account_no`='',`ifsc`='',`account_type`='',`bank_name`='',`branch_name`=''");

       // $to = $fetchotp->email;
       //               $to1 = $site->site_owner_email;
       //              $subject = "User Registration Confirmation";
                    
                    
       //              $headers = 'From: noreply@loanplus.in' . "\r\n";
       //              $headers.= 'MIME-Version: 1.0' . "\r\n";
       //              $headers.= 'Content-type: text/html;charset=UTF-8' . "\r\n";
       //              $message="Registration Confirmation,<br> ";
       //              $message.="Subject: ".$subject."<br>";
       //              $message.="Name: ".$fetchotp->name."<br>";
       //              $message.="Reference No (Retailer's Token): ".$fetchotp->reference_no."<br>";
       //              $message.="Email ID: ".$fetchotp->email."<br>";
       //               $message.="Phone: ".$fetchotp->phone."<br>";
                      
       //                 $message.="This is an autogenerated email, please do not reply to this email. Your Password is: testing";
       //              mail($to, $subject, $message, $headers);
       //               mail($to1, $subject, $message, $headers);

        header("Location: index.php");
                      // $query='';
                      //   foreach($_POST as $key=>$value) if($key != 'submit')$query .="`$key`='$value',";
                      //   $query = substr($query, 0, -1);//omit last comma
                            
                      //   mysqli_query($link,"INSERT INTO ".$prefix."user SET ".$query);
                         echo '<p class="alert alert-success" id="success-alert"><i class="fa fa-check fa-fw"></i>Registered successfully.</p>';


                        
                          
        }
                }
             

?>
<h1 class="color-5 bold">Please Enter Your OTP!</h1>

<form class="cozy" method="post" enctype="multipart/form-data">
<div class="form-group has-icon">
<input type="text" class="form-control form-control-rounded" name="otpgiven" placeholder="OTP*"> <i class="icon fas fa-sms ml-2">
</i>
</div>
<div class="form-group d-flex align-items-center justify-content-between">
<button type="submit" name="otpsubmit" class="btn btn-accent btn-rounded ml-auto">Validate <i class="fas fa-long-arrow-alt-right ml-2">
</i>
</button>
</div>
</form>
</div>
</div>
</div>
</div>
</main>
<!-- themeforest:js -->

<?php include "include/footer.php"?>